In [1]:
import random
import numpy as np

In [2]:
num = np.arange(26)
alphabet = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
num_to_alphabet = dict(zip(num, alphabet))
alphabet_to_num = dict(zip(alphabet, num))

In [3]:
def shuffle_forward(ar, seed):
    np.random.seed(seed)
    ar = np.array(ar)
    np.random.shuffle(ar)
    return ar

# シャッフルの逆操作
def shuffle_backward(ar, seed):
    order = np.arange(len(ar))
    ar_out = np.full(len(ar), -1)
    np.random.seed(seed)
    np.random.shuffle(order)
    for i, j in enumerate(order):
        ar_out[j] = ar[i]
    return ar_out

def make_pairs(ar, seed):
    np.random.seed(seed)
    np.random.shuffle(ar)
    pairs = []
    for i in range(0, len(ar) - 1, 2):
        pairs.append([ar[i], ar[i + 1]])
    return pairs

In [4]:
a = [4, 3, 1, 0, 2]
print(a)
b = shuffle_forward(a, 0)
print(b)
c = shuffle_backward(b, 0)
print(c)


[4, 3, 1, 0, 2]
[1 4 3 0 2]
[4 3 1 0 2]


In [7]:
# make enigma machine parts

class Rotor:
    def __init__(self, seed):
        self.seed = seed
        self.forward = shuffle_forward(np.arange(26), seed)
        self.backward = shuffle_backward(self.forward, seed)
    
    def encode(self, A):
        return num_to_alphabet[self.forward[alphabet_to_num[A]]]
    
    def decode(self, A):
        return num_to_alphabet[self.backward[alphabet_to_num[A]]]
    
    def rotate(self):
        self.forward = np.roll(self.forward, 1)
        self.backward = shuffle_backward(self.forward, self.seed)


class Turnover:
    def __init__(self, seed):
        self.seed = seed
        self.pairs = make_pairs(np.arange(26), seed)
        # print(self.pairs)
    
    def encode(self, A):
        for pair in self.pairs:
            if A == num_to_alphabet[pair[0]]:
                return num_to_alphabet[pair[1]]
            elif A == num_to_alphabet[pair[1]]:
                return num_to_alphabet[pair[0]]
        return A

# 関数の呼び出し回数を記録するカウンタ
class Counter:
    def __init__(self):
        self.count = 0
    
    def count_up(self):
        self.count += 1
    
    def reset(self):
        self.count = 0

class EnigmaMachine:
    def __init__(self, seed):
        self.rotor1 = Rotor(seed)
        self.rotor2 = Rotor(seed + 1)
        self.rotor3 = Rotor(seed + 2)
        self.turnover = Turnover(seed + 3)
        self.counter = Counter()
        
    def encode(self, A):
        self.counter.count_up()
        print(A, end="")
        A = self.rotor1.encode(A)
        print(A, end="")
        A = self.rotor2.encode(A)
        print(A, end="")
        A = self.rotor3.encode(A)
        print(A, end="")
        A = self.turnover.encode(A)
        print(A, end="")
        A = self.rotor3.decode(A)
        print(A, end="")
        A = self.rotor2.decode(A)
        print(A, end="")
        A = self.rotor1.decode(A)
        print(A)
        self.rotor1.rotate()
        if self.counter.count % (26) == 0:
            self.rotor2.rotate()
        if self.counter.count % 26**2 == 0:
            self.rotor3.rotate()
        return A

In [8]:
enigma_machine = EnigmaMachine(0)

chars = []
for i in range(10):
    # print(enigma_machine.encode("A"))
    chars.append(enigma_machine.encode("A"))

print(chars)

enigma_machine = EnigmaMachine(0)
chars_inversed = []
for char in chars:
    # print(enigma_machine.encode(char))
    chars_inversed.append(enigma_machine.encode(char))

print(chars_inversed)
    

ACRHFFFF
AMOTAAAD
APBATTTN
AVJXMMMA
AASWBBBN
ADDUJJJZ
AXMKYYYS
AHUSRRRA
AJCJUUUH
AEWZLLLA
['F', 'D', 'N', 'A', 'N', 'Z', 'S', 'A', 'H', 'A']
FLGGVVVV
DOXNCCCM
NBNFHHHE
AVJXMMMA
NTZIDDDE
ZXMKYYYT
SKVLZZZN
AHUSRRRA
HMOTAAAY
AEWZLLLA
['V', 'M', 'E', 'A', 'E', 'T', 'N', 'A', 'Y', 'A']


In [32]:
a

array([0, 3, 4, 1, 2])